### ISSUE TITLE
Error Failed to Open URL: unknown error

### ISSUE THREAD

**Issue by Payne69** [Fedoraware/Fedoraloader#8]
just downloaded the new Fedorware when I pressed Load it said Failed to Open URL: unknown error (I alr closed steam did that)
still didnt work pls help :))

**Comment by lnx00** [comment]
I'm pretty sure this issue is out of my control. It means that Windows wasn't able to open a connection to the download server (https://nightly.link/Fedoraware/Fedoraware/workflows/msbuild/main/Fedoraware.zip).

Since the loader and the URL seems to work fine for me and most people, it is probably a connection issue on your end. Make sure that your firewall/antivirus/government isn't blocking this URL,

**Comment by SkididSkider** [comment]
If ur using a vpn disable it same to the anti-virus. If the problem still occurs restart your pc wait 10 minutes and try agian or download c++ redistributable and direct x. If it's still not fixed ask the devs.

**Comment by SkididSkider** [comment]
> I'm pretty sure this issue is out of my control. It means that Windows wasn't able to open a connection to the download server (https://nightly.link/Fedoraware/Fedoraware/workflows/msbuild/main/Fedoraware.zip).
> 
> Since the loader and the URL seems to work fine for me and most people, it is probably a connection issue on your end. Make sure that your firewall/antivirus/government isn't blocking this URL.
> 
> I can, however, add more detailed connection error messages in the feature to find out where the culprit is.

wdym govurment LoL

**Comment by lnx00** [comment]
> wdym govurment LoL

https://en.wikipedia.org/wiki/Internet_censorship_and_surveillance_by_country
